### ISSUE TITLE
Mention the pre-built Poetry Alpine package?

### ISSUE THREAD

**Issue by johnthagen** [FrederikP/python-poetry-alpine#1]
I was looking into building Poetry dependencies on Alpine as is done in this repository (thank you for the excellent example!).

After some digging I learned that you can simply install `poetry` through Alpine's package manager. I know that this is likely slightly different than the goal of this project, but since this repo is the top hit on internet searches for "Poetry Alpine", I thought it might be worth mentioning in the README?

- https://pkgs.alpinelinux.org/packages?name=poetry&branch=edge

```Dockerfile
RUN apk add --no-cache poetry
```

**Comment by FrederikP** [comment]
Makes sense. The reason why it wasn't mentioned yet, is that I don't think that this package existed, when I created this repository/image.
